/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AXBubble: typeof import('ant-design-x-vue')['Bubble']
    CollapsePanel: typeof import('./src/components/CollapsePanel.vue')['default']
    HeaderActions: typeof import('./src/components/HeaderActions.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    KeepAliveTabsViewer: typeof import('./src/components/KeepAliveTabsViewer.vue')['default']
    PhoneInput: typeof import('./src/components/PhoneInput.vue')['default']
    PhoneNumberInput: typeof import('./src/components/PhoneNumberInput.vue')['default']
    RichEditor: typeof import('./src/components/RichEditor.vue')['default']
    RichEditorInline: typeof import('./src/components/RichEditorInline.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StickyFooterLayout: typeof import('./src/components/StickyFooterLayout.vue')['default']
    Tabs: typeof import('./src/components/Tabs.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
